[package]
name = "feed-rs"
version = "0.1.0"
authors = ["Hiroki Kumamoto <kumabook@live.jp>"]
include = [
    "**/*.rs",
    "Cargo.toml",
]
license = "MIT"
homepage = "https://github.com/kumabook/feed-rs"
repository = "https://github.com/kumabook/feed-rs.git"
description = "A simple RSS feed parser (rss 2.0, ATOM, rss 1.0)"
keywords = ["feed", "rss", "atom"]
[dependencies]
xml5ever     = "^0.7"
serde        = "^1"
serde_derive = "^1"
serde_json   = "^1"
chrono       = { version = "^0", features = ["serde"] }
uuid = { version = "^0", features = ["v4"] }
